create table test_drives (
	ID INTEGER NOT NULL auto_increment PRIMARY KEY,
	CLIENT_NAME VARCHAR(100) NOT NULL,
	CLIENT_PHONE VARCHAR(20) NOT NULL,
	DURATION INT NOT NULL,
	CAR_ID INT NOT NULL,
	SALON_ID INT NOT NULL,
	DRIVE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);
